### create ※expressではcontent-typeの設定をしないとjsonパースできないため注意

post http://localhost:8000/
Content-Type: application/json

{
    "title": "shincode",
    "body": "shincodeチュートリアルです"
}

### get
get http://localhost:8000/

### get
get http://localhost:8000/2

### put
put http://localhost:8000/2
Content-Type: application/json

{
    "title": "shincode2",
    "body": "shincodeチュートリアルです2"
}

### delete
delete http://localhost:8000/2
Content-Type: application/json

{
    "title": "shincode2",
    "body": "shincodeチュートリアルです2"
}
